defmodule Infrastructure.Dispatcher.AutogenerateValuesMiddleware do
  alias Infrastructure.Dispatcher.Pipeline

  def pipe_through(%Pipeline{} = pipeline) do
    raw_input = pipeline.data[:raw_input]
    key_type = EnumHelpers.key_type(raw_input)
    exclude = Map.keys(raw_input)

    autogenerated_values = generate_needed_values(pipeline.commands, key_type, exclude)

    Pipeline.with_data_for_command(
      pipeline,
      :raw_input,
      Map.merge(raw_input, autogenerated_values)
    )
  end

  def handle_response(%Pipeline{} = pipeline), do: pipeline
  def handle_error(%Pipeline{} = pipeline), do: pipeline

  defp generate_needed_values(command, key_type, exclude) do
    command
    |> Enum.flat_map(fn command ->
      command.__schema__(:meta)
      |> Enum.reduce([], fn {field, field_options}, values ->
        case field not in exclude && Keyword.get(field_options, :autogenerate, false) do
          true ->
            field = if key_type === :atom, do: field, else: Atom.to_string(field)
            [{field, apply(field_options[:type], :autogenerate, [])} | values]

          false ->
            values
        end
      end)
    end)
    |> Enum.into(%{})
  end
end
